#!/bin/bash

styles="default default_themed cerulean cosmo custom cyborg darkly flatly journal lumen paper readable sandstone simplex slate spacelab superhero united yeti"

rm -fr output > /dev/null
mkdir output

for i in $styles
do
    asciidoctor -a stylesheet="../css/bootstrap_$i.css" -o output/test_$i.html test.adoc
done
