#!/bin/bash

styles="default default_themed amelia cerulean cosmo cyborg flatly journal readable slate spacelab yeti"

for i in $styles
do
   echo creating css/bootstrap_$i.css
   lessc src/less/styles/$i/styles.less css/bootstrap_$i.css
done
